---
- hosts: prod
  become: yes
  gather_facts: no
  tasks:
    - name: Install Docker from repository 
      apt:
        name: docker.io
        state: present
        
    - name: Install Docker-compose from repository 
      apt:
        name: docker-compose
        state: present
               
    - name: Create Directory for projects
      file: path=/opt/docker state=directory
      
    - name: Copy NGINX image 
      copy:
        src: {{ microservice_name }}
        dest: /opt/docker/
        mode: 0755
        owner: root
        group: root
  
    - name: Create a network
      community.docker.docker_network:
        name: birzha

  
    - name: build container image
      docker_image:
        name: "{{ microservice_name_image }}":"{{ sha }}"
        build:
          path: /opt/docker/"{{ microservice_name }}"/"{{ dockerfile }}"
          source: build
        state: present
           
    - name: Run 
      docker_container:
         name: "{{ microservice_name }}"
         image: "{{ microservice_name_image }}":"{{ sha }}"
         state: started
         ports:
          - "80:80"
          - "443:443"
         networks:
           - name: birzha
         log_options:
           - tag: {{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}
          
          
